app:
  helmReleaseName: my-app-04
  registryUrls:
    minikube: 

  namespaces:
    minikube: application

  name: my-app-04
  version: 1.0.0
  baseImage: "node:16"
  
  service:
     spec:
       type: ClusterIP
     ports:
       - port: 3000
         protocol: TCP
         targetPort: 3000
         name: http
     sessionAffinity: None

  deployment:
    spec:
      progressDeadlineSeconds: 600
      revisionHistoryLimit: 10
      replicas: 1
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        spec:
          securityContext: {}
          terminationGracePeriodSeconds: 30
          containers:   
            - imagePullPolicy: IfNotPresent
              ports:
              - containerPort: 3000
                protocol: TCP
              resources:
                limits:
                  cpu: 300m
                  memory: 1G
                requests:
                  cpu: 200m
                  memory: 500M
              env:
                # - name: "var1"
                #   value: "var 1 value"
              livenessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 120
                periodSeconds: 5
              # livenessProbe:
              #   tcpSocket:
              #     port: 3000
              #   periodSeconds: 5
              #   failureThreshold: 3
              #   initialDelaySeconds: 120
              #   successThreshold: 1
              #   timeoutSeconds: 10
              # readinessProbe:
              #   tcpSocket:
              #     port: 3000
              #   periodSeconds: 5
              #   failureThreshold: 3
              #   initialDelaySeconds: 120
              #   successThreshold: 1
              #   timeoutSeconds: 1
